### ISSUE TITLE
An entity or component within a namespace generate illegal partial class.

### ISSUE THREAD

**Issue by pcloves** [MysteriousMilk/Godot.Composition#1]
The generated classes of [TestEntity](https://github.com/MysteriousMilk/Godot.Composition/blob/main/GeneratorTester/TestEntity.cs) and [TestComponent](https://github.com/MysteriousMilk/Godot.Composition/blob/main/GeneratorTester/TestComponent.cs) have syntax error:
``` C#
using Godot;
using Godot.Composition;

namespace GeneratorTester
{
    
    
    

        protected void InitializeComponent()
        {
            parent = GetParent<CharacterBody2D>();
        }
    
} 
```

As shown above, the generated code of `TestComponent` class loss it's class definition: `public partial class TestComponent : Godot.Composition.IComponent {}` around the methods. 

BTW, the `TestEntity` has the same issue.

**Comment by MysteriousMilk** [comment]
Changes from pull request #2 seem to fix the issue. Then generated files now have their class definitions restored.
