### ISSUE TITLE
CodeGenerator: missing Component class namespaces for [ComponentDependency]

### ISSUE THREAD

**Issue by biberesser** [MysteriousMilk/Godot.Composition#4]
First let me say: **Great Job!**
This little framework saves so much boilerplate while increasing code reuse.

---------------------------------------------------------------------------

**I think I found a small bug in the CodeGenerator:**

I have an `[Entity]` with multiple child components, with some `[ComponentDependency]` references between them.
Everything works fine, as long as the referenced child `[Component]` classes all have the same `namespace`.

**Actual behavior:**
The generated C# sources for the components are missing `using` statements 
for any `[ComponentDependency]` component with a different `namespace` 
than the generated component itself.
The build fails.

**expected behavior:**
Components may have `[ComponentDependency]` from any `namespace`.

---------------------------------------------------------------------------

my own component source code:

The referenced (shared) component from `namespace` "B":
```
namespace B;

[Component(typeof(Node))]
public partial class ComponentB : Node
{ ... }
```

The component from `namespace` "A" using the shared component from "B":
```
using B;

namespace A;

[Component(typeof(Node))]
[ComponentDependency(typeof(ComponentB))]
public partial class ComponentA : Node
{ ... }
```

The generated sources for `ComponentA`:
no `using` statement for namespace "B" (or a fully qualified name):
```
using Godot;
using Godot.Composition;

namespace A;

public partial class ComponentA: Godot.Composition.IComponent
{
    protected Node3D parent;
    protected ComponentB componentB; // <- ERROR
	[...]
}
```

**Error from logs:**
```
0>ComponentA_IComponent.g.cs(9,15): Error CS0246 : The type or namespace name 'ComponentB' could not be found (are you missing a using directive or an assembly reference?)
```

**Desktop:**
 - OS: Win11
 - Godot 4.2.2
 - Godot.Composition 1.2

**Comment by MysteriousMilk** [comment]
@biberesser Good catch! I will have an updated version out soon.
